name: Melody
url: http://melodycss.co
markdown: rdiscount
rdiscount:
  extensions: [smart]
pygments: true
permalink: /:title
exclude: ['.gitignore', 'melody.sublime-project', 'melody.sublime-workspace', 'node_modules', '.sass_cache', '.git', 'Gemfile', 'Gemfile.lock', 'src', 'gulpfile.js', 'README.md', 'gulpfile.js', 'package.json']
encoding: utf-8